---
title: "Homework 2"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load-pkg}
# Add additional packages you need
library(tidyverse)

```


## Import Data

```{r data-import}
# Use R to import the data file `salary.txt`. 

```

## Model Equation

Example:
$$salary_i = \beta_0 + \beta_1 time_i + \beta_2 pub_i + e_i$$
$$e_i \sim N(0, \sigma)$$
    
## Multiple Regression Analysis

```{r reg-model}
# Run regression using lm()

```

### Table of coefficients

```{r reg-table}
# Summarize your regression coefficients in a table. 

```

### Regression slopes of [Predictor 1] and [Predictor 2] predicting salary

```{r plot-coef}
# Insert code for plotting the slope. You can use the 
# `sjPlot::plot_model(..., show.data = TRUE)` function.

```

### Interpretation

[E.g., based on the model, for two people with the same level of [predictor X2], the person with one unit higher on [predictor X1] is expected to report a higher salary by $XXX.]

### Simulation

[The only change you need to change should be `m3` in the following code.]

```{r sim}
# Simulate 100 data sets based on your model results by modifying the following
# codes
your_model <- m3  # change `m3` to the object name of your regression model
# Set the seed so that you always get the same simulated data set 
set.seed(1331)
# No need to change the following
num_simulations <- 100
# Simulate new salary variables
simulated_salary100 <- simulate(your_model, nsim = num_simulations)
# Placeholders for storing simulation results
simulated_slopes <- matrix(nrow = num_simulations, ncol = 2, 
                           dimnames = list(NULL, 
                                           c("slopes_x1", "slopes_x2")))
# Run regression 100 times, each time using a different simulated salary outcome
for (i in 1:num_simulations) {
  reg_model_sim <- update(your_model, 
                          simulated_salary100[ , i] ~ .)
  # Store slope results
  simulated_slopes[i, ] <- coef(reg_model_sim)[2:3]
}
# Plot the sampling distributions
as_tibble(simulated_slopes) %>% 
  pivot_longer(1:2, names_to = "predictor", 
               values_to = "slopes", 
               names_prefix = "slopes_") %>% 
  ggplot(aes(x = slopes)) + 
  geom_histogram() + 
  facet_wrap(~ predictor, scales = "free_x")
```

[Write a short paragraph to discuss what the two histograms tell you, and  reflect on the process of simulating the data.]

### Interaction plot

```{r inter-plot}
# Include interaction in lm()

# Interaction plot

```

