project:
  type: website
  render:
    - index.qmd
    - post.qmd
    - publication.qmd
    - software.qmd
    - cv.qmd
    - "posts/"
    - "slide/"
  resources:
    - "slide/"

website:
  title: "Mark Lai"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: post.qmd
        text: Posts
      - href: publication.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: cv.qmd
        text: CV
      # - about.qmd
  page-footer: "Copyright 2023, Hok Chio (Mark) Lai"
  google-analytics: "G-NLMBWPMFDG"

format:
  html:
    theme: minty
    css: styles.css
    toc: true



