---
title: "Software"
---

## [*bootmlm*](https://github.com/marklhc/bootmlm)

An R package for bootstrap resampling for multilevel models.

## [*pinsearch*](https://github.com/marklhc/pinsearch)

An R package to automate the process of performing specification search in identifying noninvariant items.

## [*R2spa*](https://github.com/Gengrui-Zhang/R2spa)

*With Winnie Wing-Yee Tse, Yixiao Li, & Gengrui Zhang*

A free and open-source R package that performs two-stage path analysis (2S-PA).

## [*semptools*](https://github.com/sfcheung/semptools)

*By Shu Fai Cheung*

Helper functions for modifying (postprocessing) plots generated by the `semPlot` package.

## [*semfindr*](https://github.com/sfcheung/semfindr)

*By Shu Fai Cheung*

A find(e)r of influential cases in structural equation modeling based mainly on the sensitivity analysis procedures presented by [Pek and MacCallum (2011)](https://www.tandfonline.com/doi/abs/10.1080/00273171.2011.561068).

## [*unbiasr*](https://github.com/mmm-usc/unbiasr)

*With Clay Cantrell, Yichi Zhang and Meltem Ozcan*

An R package for implementing the classification accuracy analysis procedure for partial invariance.

- [Shiny application](https://mmmlabusc.shinyapps.io/partinvshinyui/)