---
title: Mixed Factorial ANOVA in R
author: marklai
date: '2021-03-29'
slug: mixed-factorial-anova-in-r
categories:
  - Statistics
tags:
  - statistics
  - ANOVA
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-29T09:59:03-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: true
    df_print: paged
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>
<link href="{{< blogdown/postref >}}index_files/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/pagedtable/js/pagedtable.js"></script>

<div id="TOC">
<ul>
<li><a href="#load-required-packages">Load Required Packages</a></li>
<li><a href="#data-description">Data Description</a>
<ul>
<li><a href="#data-import">Data Import</a></li>
<li><a href="#mixed-anova">Mixed ANOVA</a>
<ul>
<li><a href="#anova-table">ANOVA Table</a></li>
<li><a href="#plot">Plot</a></li>
</ul></li>
<li><a href="#sample-result-reporting">Sample Result Reporting</a></li>
</ul></li>
</ul>
</div>

<div id="load-required-packages" class="section level1">
<h1>Load Required Packages</h1>
<pre class="r"><code>library(afex)</code></pre>
<pre><code>## Loading required package: lme4</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;car&#39;:
##   method                          from
##   influence.merMod                lme4
##   cooks.distance.influence.merMod lme4
##   dfbeta.influence.merMod         lme4
##   dfbetas.influence.merMod        lme4</code></pre>
<pre><code>## ************
## Welcome to afex. For support visit: http://afex.singmann.science/</code></pre>
<pre><code>## - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
## - Methods for calculating p-values with mixed(): &#39;KR&#39;, &#39;S&#39;, &#39;LRT&#39;, and &#39;PB&#39;
## - &#39;afex_aov&#39; and &#39;mixed&#39; objects can be passed to emmeans() for follow-up tests
## - NEWS: library(&#39;emmeans&#39;) now needs to be called explicitly!
## - Get and set global package options with: afex_options()
## - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
## - For example analyses see: browseVignettes(&quot;afex&quot;)
## ************</code></pre>
<pre><code>## 
## Attaching package: &#39;afex&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmer</code></pre>
<pre class="r"><code>library(tidyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;tidyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:Matrix&#39;:
## 
##     expand, pack, unpack</code></pre>
</div>
<div id="data-description" class="section level1">
<h1>Data Description</h1>
<p>The fictional data set is part of the data library of the <a href="https://jasp-stats.org/">JASP software</a>, and is from the book by Field (2017)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. Here it only contains a subset of the data, where 10 men and 10 women for three speed-dating partners. All three partners were low in attractiveness (however defined), but varied in charisma: high, some, or none.</p>
<div id="data-import" class="section level2">
<h2>Data Import</h2>
<pre class="r"><code>charisma_data &lt;- read.csv(&quot;charisma_ugly.csv&quot;)
# Show the first six rows
head(charisma_data)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["participant"],"name":[1],"type":["chr"],"align":["left"]},{"label":["gender"],"name":[2],"type":["chr"],"align":["left"]},{"label":["ug_high"],"name":[3],"type":["int"],"align":["right"]},{"label":["ug_some"],"name":[4],"type":["int"],"align":["right"]},{"label":["ug_none"],"name":[5],"type":["int"],"align":["right"]}],"data":[{"1":"P01","2":"Male","3":"67","4":"50","5":"47","_rn_":"1"},{"1":"P02","2":"Male","3":"53","4":"48","5":"46","_rn_":"2"},{"1":"P03","2":"Male","3":"48","4":"48","5":"48","_rn_":"3"},{"1":"P04","2":"Male","3":"58","4":"40","5":"53","_rn_":"4"},{"1":"P05","2":"Male","3":"57","4":"50","5":"45","_rn_":"5"},{"1":"P06","2":"Male","3":"51","4":"42","5":"43","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="mixed-anova" class="section level2">
<h2>Mixed ANOVA</h2>
<p>In R, one needs to first convert the data to a long format, so that each row represents an observation (instead of a person). In this data, there were 60 observations.</p>
<pre class="r"><code># First, convert to long format data
long_data &lt;- tidyr::pivot_longer(
  charisma_data,
  cols = ug_high:ug_none,
  # name of IV
  names_to = &quot;charisma&quot;,
  # remove the &quot;ug_&quot; prefix
  names_prefix = &quot;ug_&quot;, 
  # name of DV
  values_to = &quot;rating&quot;
)
long_data</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["participant"],"name":[1],"type":["chr"],"align":["left"]},{"label":["gender"],"name":[2],"type":["chr"],"align":["left"]},{"label":["charisma"],"name":[3],"type":["chr"],"align":["left"]},{"label":["rating"],"name":[4],"type":["int"],"align":["right"]}],"data":[{"1":"P01","2":"Male","3":"high","4":"67"},{"1":"P01","2":"Male","3":"some","4":"50"},{"1":"P01","2":"Male","3":"none","4":"47"},{"1":"P02","2":"Male","3":"high","4":"53"},{"1":"P02","2":"Male","3":"some","4":"48"},{"1":"P02","2":"Male","3":"none","4":"46"},{"1":"P03","2":"Male","3":"high","4":"48"},{"1":"P03","2":"Male","3":"some","4":"48"},{"1":"P03","2":"Male","3":"none","4":"48"},{"1":"P04","2":"Male","3":"high","4":"58"},{"1":"P04","2":"Male","3":"some","4":"40"},{"1":"P04","2":"Male","3":"none","4":"53"},{"1":"P05","2":"Male","3":"high","4":"57"},{"1":"P05","2":"Male","3":"some","4":"50"},{"1":"P05","2":"Male","3":"none","4":"45"},{"1":"P06","2":"Male","3":"high","4":"51"},{"1":"P06","2":"Male","3":"some","4":"42"},{"1":"P06","2":"Male","3":"none","4":"43"},{"1":"P07","2":"Male","3":"high","4":"61"},{"1":"P07","2":"Male","3":"some","4":"44"},{"1":"P07","2":"Male","3":"none","4":"45"},{"1":"P08","2":"Male","3":"high","4":"56"},{"1":"P08","2":"Male","3":"some","4":"54"},{"1":"P08","2":"Male","3":"none","4":"47"},{"1":"P09","2":"Male","3":"high","4":"54"},{"1":"P09","2":"Male","3":"some","4":"58"},{"1":"P09","2":"Male","3":"none","4":"45"},{"1":"P10","2":"Male","3":"high","4":"63"},{"1":"P10","2":"Male","3":"some","4":"49"},{"1":"P10","2":"Male","3":"none","4":"39"},{"1":"P11","2":"Female","3":"high","4":"93"},{"1":"P11","2":"Female","3":"some","4":"54"},{"1":"P11","2":"Female","3":"none","4":"52"},{"1":"P12","2":"Female","3":"high","4":"85"},{"1":"P12","2":"Female","3":"some","4":"60"},{"1":"P12","2":"Female","3":"none","4":"45"},{"1":"P13","2":"Female","3":"high","4":"89"},{"1":"P13","2":"Female","3":"some","4":"53"},{"1":"P13","2":"Female","3":"none","4":"44"},{"1":"P14","2":"Female","3":"high","4":"83"},{"1":"P14","2":"Female","3":"some","4":"58"},{"1":"P14","2":"Female","3":"none","4":"47"},{"1":"P15","2":"Female","3":"high","4":"80"},{"1":"P15","2":"Female","3":"some","4":"43"},{"1":"P15","2":"Female","3":"none","4":"48"},{"1":"P16","2":"Female","3":"high","4":"79"},{"1":"P16","2":"Female","3":"some","4":"47"},{"1":"P16","2":"Female","3":"none","4":"40"},{"1":"P17","2":"Female","3":"high","4":"85"},{"1":"P17","2":"Female","3":"some","4":"47"},{"1":"P17","2":"Female","3":"none","4":"47"},{"1":"P18","2":"Female","3":"high","4":"87"},{"1":"P18","2":"Female","3":"some","4":"51"},{"1":"P18","2":"Female","3":"none","4":"46"},{"1":"P19","2":"Female","3":"high","4":"90"},{"1":"P19","2":"Female","3":"some","4":"53"},{"1":"P19","2":"Female","3":"none","4":"45"},{"1":"P20","2":"Female","3":"high","4":"96"},{"1":"P20","2":"Female","3":"some","4":"46"},{"1":"P20","2":"Female","3":"none","4":"47"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>mixed_anova &lt;- aov_ez(
  id = &quot;participant&quot;,
  dv = &quot;rating&quot;,
  data = long_data,
  between = &quot;gender&quot;,
  within = &quot;charisma&quot;
)</code></pre>
<pre><code>## Converting to factor: gender</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: gender</code></pre>
<pre class="r"><code>test_sphericity(mixed_anova)</code></pre>
<pre><code>## Warning in summary.Anova.mlm(object$Anova, multivariate = FALSE): HF eps &gt; 1
## treated as 1</code></pre>
<pre><code>##                 Test statistic p-value
## charisma               0.94392 0.61226
## gender:charisma        0.94392 0.61226</code></pre>
<p>When one or more independent variable is a within-subject variable, mixed or repeated-measure ANOVA requires testing the assumption of sphericity. Here, the Mauchly’s test of sphericity provided insufficient evidence that the assumption of sphericity was violated, <span class="math inline">\(p = .612\)</span>.</p>
<div id="anova-table" class="section level3">
<h3>ANOVA Table</h3>
<pre class="r"><code>mixed_anova</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: rating
##            Effect          df   MSE          F  ges p.value
## 1          gender       1, 18 25.42  71.82 *** .586   &lt;.001
## 2        charisma 1.89, 34.09 24.42 167.84 *** .857   &lt;.001
## 3 gender:charisma 1.89, 34.09 24.42  58.10 *** .676   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1
## 
## Sphericity correction method: GG</code></pre>
<p>Note that the result by default applies the Greenhousse-Geisser correction for violations of the sphericity assumption, but since the Mauchly’s test was not statistically significant, the results would be similar with or without the correction. Also note that the result here reports the generalized <span class="math inline">\(\eta^2\)</span> (the <code>ges</code> column), which is different from some other software. See the documentation of the <code>?afex::nice</code> page.</p>
</div>
<div id="plot" class="section level3">
<h3>Plot</h3>
<pre class="r"><code>afex_plot(mixed_anova, x = &quot;charisma&quot;, trace = &quot;gender&quot;)</code></pre>
<pre><code>## Warning: Panel(s) show a mixed within-between-design.
## Error bars do not allow comparisons across all means.
## Suppress error bars with: error = &quot;none&quot;</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
</div>
<div id="sample-result-reporting" class="section level2">
<h2>Sample Result Reporting</h2>
<caption>
<span id="tab:unnamed-chunk-3">Table 1: </span>
</caption>
<div custom-style="Table Caption">
<em>Two-Way ANOVA Statistics for Study Variables</em>
</div>
<table>
<thead>
<tr class="header">
<th align="left">Effect</th>
<th align="left"><span class="math inline">\(\hat{\eta}^2_G\)</span></th>
<th align="left"><span class="math inline">\(F\)</span></th>
<th align="left"><span class="math inline">\(\mathit{df}^{\mathrm{GG}}\)</span></th>
<th align="left"><span class="math inline">\(\mathit{df}_{\mathrm{res}}^{\mathrm{GG}}\)</span></th>
<th align="left"><span class="math inline">\(\mathit{MSE}\)</span></th>
<th align="left"><span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Gender</td>
<td align="left">.586</td>
<td align="left">71.82</td>
<td align="left">1</td>
<td align="left">18</td>
<td align="left">25.42</td>
<td align="left">&lt; .001</td>
</tr>
<tr class="even">
<td align="left">Charisma</td>
<td align="left">.857</td>
<td align="left">167.84</td>
<td align="left">1.89</td>
<td align="left">34.09</td>
<td align="left">24.42</td>
<td align="left">&lt; .001</td>
</tr>
<tr class="odd">
<td align="left">Gender <span class="math inline">\(\times\)</span> Charisma</td>
<td align="left">.676</td>
<td align="left">58.10</td>
<td align="left">1.89</td>
<td align="left">34.09</td>
<td align="left">24.42</td>
<td align="left">&lt; .001</td>
</tr>
</tbody>
</table>
<p>A two-way mixed ANOVA was conducted, with gender (female vs. male) as the between-subject independent variable and charisma (high, some, none) as the within-subject independent variable. There was a significant main effect of charisma, <span class="math inline">\(F(1.89, 34.09) = 167.84\)</span>, <span class="math inline">\(\mathit{MSE} = 24.42\)</span>, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(\hat{\eta}^2_G = .857\)</span>. As shown in the figure, overall female participants provided a higer rating than male participants. There was also a significant main effect of gender, <span class="math inline">\(F(1, 18) = 71.82\)</span>, <span class="math inline">\(\mathit{MSE} = 25.42\)</span>, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(\hat{\eta}^2_G = .586\)</span>. As shown in the figure, ratings were higher for partners who had high charisma. Finally, there was a significant charisma <span class="math inline">\(\times\)</span> gender interaction, <span class="math inline">\(F(1.89, 34.09) = 58.10\)</span>, <span class="math inline">\(\mathit{MSE} = 24.42\)</span>, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(\hat{\eta}^2_G = .676\)</span>. As shown in the figure, while the ratings were similar between female and male participants for partners who had some or no charisma, female participants gave higher ratings for the partner with high charisma, as compared to male participants.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Field, A. P. (2017). <em>Discovering Statistics Using IBM SPSS Statistics</em> (5th ed.). Sage.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
