---
title: Homework 1
date: '2020-08-02'
slug: homework-1
categories: []
tags: []
linktitle: Homework 1
summary: ~
lastmod: '2020-07-30T22:24:45-07:00'
type: docs
menu:
  psyc575:
    parent: Week 1
    weight: 3
---

## Learning Objective

- Identify the types of multilevel data structure in different research scenarios

## Assignment Description 

In this first assignment, you will first introduce yourself on the Slack channel. You will then find a published research article in your area of research in which the authors have used a multilevel analysis, and indicate the information on a Google Sheet. Complete the two parts (self-introduction and article search) of the assignment by **August 21**. This assignment is worth 6 points. 

## Steps

1. Introduce yourself on Slack
    a. Go to the Slack channel for this course. You will need to sign on. If you're new to Slack, check out [this USC guide](https://keepteaching.usc.edu/students/student-toolkit/classroom/slack/)
    b. In the **Message** box, write 
        i. a brief description of your background (e.g., your major, research interest)
        ii. the reason of taking this course
        iii. your experience of using R or other statistical programs/packages
        iv. something else about yourself that you want to share with the class
    c. (Optional) Review and comment on peer messages using threads
2. Find a journal article that reported results of a multilevel analysis in your field.
3. Go to the Google spreadsheet at https://docs.google.com/spreadsheets/d/18jdCyfu5eqFQ30YblABft-o5F5ozY5SdO2E7Z3ZYJCs. In a new row, record the following information from the article:
    a. The full reference of the article (with the DOI)
    b. The research question (summarized in one sentence)
    c. The unit of each level (e.g., students, classrooms, schools; hospitals, states; repeated measures, persons)
    d. The sample size for each level
    e. Whether the authors present equation(s) for their model
    f. The software used for the multilevel analyses
    g. Did the authors include any tables to present the results? If yes, record the types of tables were those (e.g., correlations, descriptives, fixed effect coefficients)?
    h. Did the authors include any graphs to present the results? If yes, what types of graphs were those (e.g., path diagrams, scatterplots)?

## Grading 

Your instructor will be grading on completeness of this first assignment.

## Additional Notes

Remember that multilevel modeling may be called a different name in some research area. You may post your questions to the Discussion Board to get help from your peers and instructor. 
