---
title: Homework 5
date: '2020-09-03'
slug: homework-5
categories: []
tags: []
linktitle: Homework 5
summary: ~
lastmod: '`r Sys.Date()`'
type: docs
menu:
  psyc575:
    parent: Week 5
    weight: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
comma <- function(x) format(x, digits = 2, big.mark = ",")
```

## Learning Objective

- Evaluate published research that uses multilevel modeling

## Assignment Description 

In this assignment, you will evaluate a published article, presumably the article you read in HW 1 (but you can use another article), using the Desiderata table in McCoach (2019, pp. 293--294). Most likely you only need to read the method and the results section of the paper. Because we have not covered every topic in that table, you will be evaluating the article based on a subset of the desiderata. However, other points in the table are still important---just that we haven't formally introduced them yet. The goal is that by analyzing an article, you will be able to identify what needs to be reported in your own multilevel analyses, for the class project and for your future research. 

In addition, because we will need to do Bayesian MLM moving forward, it's important you have the `rstan` package installed properly on your computer, as part of this assignment. 

## Steps

1. Make a copy or Download the ["HW 5 Template" file](https://docs.google.com/spreadsheets/d/14euZtytxkIPNUwcYzg5baGh0aLFyz50Wko5BtWobGcI). One way to do it is to make a copy of the file to your own Google Drive. 
### Part 1

2. Follow the instruction on https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started to install the `rstan` package, which will be needed moving forward. Pay attention to the instruction as installing `rstan` is not as straight forward as installing other packages, depending on what operating system and what version of it you are using. 

3. After installing `rstan`, run the following and copy the output to the spreadsheet. 
```r
sessioninfo::package_info("rstan", dependencies = FALSE)
```

4. Run the following in R, which, if run successfully, should give a graph. Copy the resulting graph to the spreadsheet to show that you have successfully installed the `rstan` package. Please make sure it works on your computer as future assignments will require using `rstan`. 
```r
library(rstan)
scode <- "
parameters {
  real y[2]; 
} 
model {
  y[1] ~ normal(0, 1);
  y[2] ~ double_exponential(0, 2);
} 
"
fit1 <- stan(model_code = scode, iter = 10, verbose = FALSE) 
plot(fit1)
```

### Part 2

5. Find an article that uses multilevel modeling in your field. It can be the article you used for HW 1. 
6. Imagine you're a reviewer for the article. From the list of desiderata on the template, evaluate whether the article meets each of the reporting requirement.
    i. If the article meets the requirement, copy the sentences that are relevant. For tables/figures, you can cut the picture into the spread sheet. 
    ii. If the article does not report the required information, write a sentence to suggest what the authors can do. You can use the wordings from the desiderata. 
7. Double check to make sure you have one cell filled for each row (i.e., whether Column B or Column C). 
8. Submit your work to Blackboard. It can be in Excel or in PDF (but make sure all your answers are shown).

## Grading 

Your instructor will use the rubric on Slack to grade this assignment. 

## Additional Notes

You may post your questions to the Slack channel to get help from your peers and instructor. 
