---
title: Homework 8
date: '2020-10-10'
slug: homework-8
categories: []
tags: []
linktitle: Homework 8
summary: ~
lastmod: '`r Sys.Date()`'
type: docs
output:
  blogdown::html_page:
    df_print: paged
menu:
  psyc575:
    parent: Week 10
    weight: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
comma <- function(x) format(x, digits = 2, big.mark = ",")
```

## Learning Objective

- Independently analyze real data using statistical software for multilevel modeling
- Effectively communicate findings

## Assignment Description 

In this assignment, you will use the data set from the lecture and fit a similar model. Specifically, you'll use `stressor` and `weekend` to predict `mood`, and write as if you're reporting the results in a research report. You can use the example from pp. 387--388 of [Hoffman (2014)](https://www-taylorfrancis-com.libproxy1.usc.edu/books/9781315744094/chapters/10.4324/9781315744094-17) as a reference. 

## Steps

1. In R, use `stressor` and `weekend` to predict `mood`, using the same data from the lecture. Make sure to decompose the effect of `stressor`. 
2. Report your results in Rmd, like you would do when writing the result section of a research report. You can reference the paragraphs from Hoffman (2014, pp. 387, "The prediction of daily . . ." to p. 388, "We then examined . . .", and then p. 389, "The effects of daily stressors and their interactions . . ."); however, do not plagiarize. Be sure to include:
    a. Model equations
    b. A table of coefficients (numbered with a caption)
    c. A graph showing how `stressor` relates to `mood` (numbered with an appropriate description)
    d. Parameter estimates (both point and 95% CI) and interpretations of the results
3. Knit your Rmd file to HTML/PDF/Word, and submit the knitted file to Blackboard. 

## Grading 

Your instructor will use the rubric on Slack to grade this assignment. 

## Additional Notes

You may post your questions to the Slack channel to get help from your peers and instructor. 

