---
title: Prospectus
date: '2020-09-22'
slug: prospectus
categories: []
tags: []
linktitle: Prospectus
summary: ~
lastmod: '`r Sys.Date()`'
type: docs
output:
  blogdown::html_page:
    df_print: paged
menu:
  psyc575:
    parent: Week 7
    weight: 3
---

## Learning Objective

- Apply multilevel modeling in a research project

## Assignment Description 

A prospectus about your project should be submitted by **Monday, October 5, 2020**. The prospectus should contain a concise description of what you (or your group) plan to do for your project, including a brief description of your research question(s), study design, structure of the data, and a preliminary plan for statistical analysis. The prospectus should be limited to 1 single-spaced page (excluding references and any supplemental materials).

In addition, the project requires you to create a repository for your project so that you can share your analytic scripts. You can also upload data files (if it's sharable and without identifiable information) any supplemental materials, but those are optional. Your prospectus should include a link to the repository you created for your project. 

Note: If you're working as a group, only one member needs to submit the prospectus. 

## Steps

1. Before you start, schedule an appointment with your instructor during the week of October 5--12 (Link will be available on Thursday)
2. You can use R Markdown or other word processing software for writing your prospectus. 
3. Write down your name(s)
4. Indicate whether you/your group will do a paper or a presentation. Only one paper/presentation is required for each group. 
5. Include the following in the prospectus
    a. A brief description of your research question(s) and relevant background
    b. Design and structure of your data
    c. A preliminary plan for statistical analysis
    d. Additional information that would facilitate discussions (e.g., network graphs of the data structure, flow chart of experimental designs, etc)
6. Create a repository for your project. One easy way is to do it with the Open Science Framework (OSF; see https://help.osf.io/hc/en-us/articles/360019737594-Create-a-Project), and you can log in with your USC credential (go to https://accounts.osf.io/login, then select "Sign in through institution"). Alternatively, if you're familiar with GitHub (or other similar platforms), you can use that as well. 
7. At the end of your prospectus (before references and any supplemental materials), include the following statement:
> The data analytic scripts and supplemental materials for this project will be available at [insert the link to your repository]

    * Note: If your repository is private, you'll need to create a view-only link: https://help.osf.io/hc/en-us/articles/360019930333-Create-a-View-only-Link-for-a-Project
8. Submit your prospectus (in PDF/WORD) to Blackboard. 

## Grading 

Your instructor will use the rubric on Slack to grade this assignment. 

## Additional Notes

You may post your questions to the Slack channel to get help from your peers and instructor. 
