---
title: Week 12
linktitle: Week 12
type: docs
date: "2020-10-25T13:25:00+01:00"
draft: false
lastmod: '`r Sys.Date()`'
menu:
  psyc575:
    name: Week 12
    weight: 12

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 1
---

## Week Learning Objectives

By the end of this module, you will be able to 

- Describe the problems of using a regular multilevel model for a binary outcome variable
- Write model equations for multilevel logistic regression
- Estimate intraclass correlations for binary outcomes
- Plot model predictions in probability unit

## Instructions

1. Review the resources (lecture videos and slides)
2. Complete the assigned readings
    * Snijders & Bosker ch 17.1--17.4 (you can skip 17.2.1)
3. Attend the synchronous Zoom session to do an exercise on identifying data structure
    * If unable to attend, complete an alternative assignment
4. Complete peer review for two of your peers' postings (due Monday November 9, 9 am PST)
5. Complete [Homework 9](../homework-9)
6. (Optional) Read the [bonus material](../rcode11_bonus) on binomial logistic model

