---
title: Week 5
linktitle: Week 5
type: docs
date: "2020-09-05T21:09:00+01:00"
draft: false
lastmod: '`r Sys.Date()`'
menu:
  psyc575:
    name: Week 5
    weight: 5

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 1
---

## Week Learning Objectives

By the end of this module, you will be able to 

- Describe conceptually what **likelihood function** and maximum likelihood estimation are
- Describe the differences between **maximum likelihood** and **restricted maximum likelihood**
- Conduct statistical tests for fixed effects
- Use the **likelihood ratio test** to test random slopes
- Report results of a multilevel analysis based on established guidelines

## Instructions

1. Review the resources (lecture videos and slides)
2. Complete the assigned readings
    * Snijders & Bosker ch 4.7, 6
    * [McCoach (2019 chapter)](https://www-taylorfrancis-com.libproxy2.usc.edu/books/e/9781315755649/chapters/10.4324/9781315755649-22) (USC SSO required): needed for HW 5
3. Attend the synchronous Zoom session to do an exercise on estimation methods 
    * If unable to attend, complete an alternative assignment
4. Complete [Homework 5](../homework-5)
5. (Optional) fill out the early/mid-semester feedback survey on Blackboard
