---
title: Week 9
linktitle: Week 9
type: docs
date: "2020-10-03T21:09:00+01:00"
draft: false
lastmod: '`r Sys.Date()`'
menu:
  psyc575:
    name: Week 9
    weight: 9

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 1
---

## Week Learning Objectives

By the end of this module, you will be able to 

- Describe the similarities and differences between longitudinal data and cross-sectional clustered data
- Perform some basic **attrition analyses**
- Specify and run **growth curve analysis**
- Analyze models with **time-invariant covariates** (i.e., lv-2 predictors) and interpret the results

## Instructions

1. Review the resources (lecture videos and slides)
2. Complete the assigned readings
    * Snijders & Bosker ch 15 (you can skip 15.1.3 and 15.1.4)
3. Attend the synchronous Zoom session to do an exercise on identifying data structure
    * If unable to attend, complete an alternative assignment
4. Complete [Homework 7](../homework-7)
5. Additional resources for learning MLM for longitudinal data analysis
    * [This excellent book by Hoffman (2014)](https://www-taylorfrancis-com.libproxy2.usc.edu/books/9781315744094) (USC SSO required)
