---
title: Week 6
linktitle: Week 6
type: docs
date: "2020-09-10T21:09:00+01:00"
draft: false
lastmod: '`r Sys.Date()`'
menu:
  psyc575:
    name: Week 6
    weight: 6

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 1
---

{{% alert note %}}
The topics for Week 6 and Week 7 have been swapped
{{% /alert %}}

## Week Learning Objectives

By the end of this module, you will be able to 

- Identify the correct levels with experimental studies
- Describe designs with crossed random levels
- Assign variables to appropriate levels, and tell which variables can have random slopes at which levels
- Compute a version of effect size ($d$) for experimental data

## Instructions

1. Review the resources (lecture videos and slides)
2. Complete the assigned readings
    * Snijders & Bosker 13.1
    * [Hoffman & Rovine (2007)](https://link.springer.com/content/pdf/10.3758/BF03192848.pdf)
3. Attend the synchronous Zoom session to do an exercise on identifying data structure
    * If unable to attend, complete an alternative assignment
4. Think about your project---Prospectus will be due in two weeks (Monday, October 5, at 9 am PDT)
5. No HW due this week, but you may start ahead with [HW 6](../homework-6), which is due next week
6. Additional resources for learning MLM for experimental designs
    * [This paper](https://www.annualreviews.org/doi/abs/10.1146/annurev-psych-122414-033702) by Judd et al. 
