---
title: Week 7
linktitle: Week 7
type: docs
date: "2020-09-10T21:09:00+01:00"
draft: false
lastmod: '`r Sys.Date()`'
menu:
  psyc575:
    name: Week 7
    weight: 7

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 1
---

{{% alert note %}}
The topics for Week 6 and Week 7 have been swapped
{{% /alert %}}

## Week Learning Objectives

By the end of this module, you will be able to 

- Describe the benefits of Bayesian estimation methods for MLM
- Use relevant statistical vocabulary to describe Bayesian MLM
    * **Prior** and **posterior** distributions
    * Credible intervals
- Assess model convergence from MCMC sampling

## Instructions

1. Review the resources (lecture videos and slides)
2. Complete the assigned readings
    * Snijders & Bosker 12.1
    * [Hamaker & Klugkist (2011 chapter)]() (USC SSO required)
3. Attend the synchronous Zoom session to do an exercise on Bayesian estimation methods 
    * If unable to attend, complete an alternative assignment
4. Complete your (or your group's) project prospectus (due Monday October 5)
5. Complete [Homework 6](../homework-6)
6. Additional resources for learning Bayesian methods
    * [This paper](https://link.springer.com/article/10.3758/s13423-016-1221-4) by Kruschke and Liddell
    * [The notes of the Bayesian course by myself](https://psyc-bayes-notes.netlify.com)
